name: Validate links

on:
  pull_request: null
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

jobs:
  link-checker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2.1.0
      - name: Create issue
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link checker report
          labels: 'report, automated-issue'
          content-filepath: ./lychee/out.md
      - name: Assign issues
        if: env.lychee_exit_code != 0
        uses: gustavofreze/auto-assign@1.0.0
        with:
          assignees: '${{ secrets.ASSIGNEES }}'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          allow_self_assign: 'true'
          allow_no_assignees: 'true'
          assignment_options: 'ISSUE'